navigate = "navigate"
compare_text = "compare text"
click = "click"
get_text = "get text"
hover = "hover"
print_all_elements = "print all elements"
print_step_description = "print step description"
print_child_elements = "print child elements"
refresh = "refresh"
right_click = "right click"
send_keys = "send keys"
switch_to_window = "switch to window"
take_screenshot = "take screenshot"
wait = "wait"
get_json_from_api = "get json from api"
wait_for_element_presence = "wait for element presence"
wait_for_clickable_element = "wait for clickable element"
select_dropdown_by_value = "select dropdown by value"
select_all_elements = "select all elements"
get_all_xpath_and_css_selectors = "get all xpath and css selectors"
get_table_information = "get table information"
save_har_file = "save har file"
save_complete_har_file = "save complete har file"
check_page_tagging = "check page tagging"

perform_wcag_ada_checks = "perform wcag ada checks"
# Check image command removed in favor of perform wcag ada checks
# command, which can check all wcag and ada elements
# check_image_tags_for_alt_text = "check image alt text"
connect_to_database = "connect to database"
query_database = "query database"


